scene.setBackgroundColor(15)
music.play(music.stringPlayable("C A G F B A G C5 ", 500), music.PlaybackMode.UntilDone)
let play1 = sprites.create(img`
    .........................
    .........22222...........
    ........2222222..........
    ........2222222..........
    ........eeeeeee..........
    ........e11d11e..........
    .......ee1fdf1ee.........
    .......eedddddee.........
    ........eddddde..........
    ........eddfdde..........
    .........eddde..ee.......
    ..........eee...ee.......
    ........eeeeeee.ee.......
    ......eeedddddeeee.......
    .....eeeedddddeee........
    .....ee.eddddde..ee......
    .....ee.eddddde...ee.....
    .....ee.eddddde....ee....
    ........edddddee....e....
    ........edddddeee..ee....
    ........eeeeeee.eeee.....
    ........ee...ee..........
    ........ee...ee..........
    ......2222...2222........
    ......2222...2222........
    `, SpriteKind.Player)
let play2 = sprites.create(img`
    .........................
    ....99999................
    ...9999999...............
    ...9999999...............
    ...eeeeeee...............
    ...e11d11e...............
    ..ee1fdf1ee..............
    ..eedddddee..............
    ...eddddde...............
    ...eddfdde...............
    ....eddde..ee............
    .....eee...ee............
    ...eeeeeee.ee............
    .eeedddddeeee............
    eeeedddddeee.............
    ee.eddddde..ee...........
    ee.eddddde...ee..........
    ee.eddddde....ee.........
    ...edddddee....e.........
    ...edddddeee..ee.........
    ...eeeeeee.eeee..........
    ...ee...ee...............
    ...ee...ee...............
    .9999...9999.............
    .9999...9999.............
    `, SpriteKind.Player)
let play3 = sprites.create(img`
    .........................
    ....77777................
    ...7777777...............
    ...7777777...............
    ...eeeeeee...............
    ...e11d11e...............
    ..ee1fdf1ee..............
    ..eedddddee..............
    ...eddddde...............
    ...eddfdde...............
    ....eddde..ee............
    .....eee...ee............
    ...eeeeeee.ee............
    .eeedddddeeee............
    eeeedddddeee.............
    ee.eddddde..ee...........
    ee.eddddde...ee..........
    ee.eddddde....ee.........
    ...edddddee....e.........
    ...edddddeee..ee.........
    ...eeeeeee.eeee..........
    ...ee...ee...............
    ...ee...ee...............
    .7777...7777.............
    .7777...7777.............
    `, SpriteKind.Player)
let play4 = sprites.create(img`
    .........................
    ....55555................
    ...5555555...............
    ...5555555...............
    ...eeeeeee...............
    ...e11d11e...............
    ..ee1fdf1ee..............
    ..eedddddee..............
    ...eddddde...............
    ...eddfdde...............
    ....eddde..ee............
    .....eee...ee............
    ...eeeeeee.ee............
    .eeedddddeeee............
    eeeedddddeee.............
    ee.eddddde..ee...........
    ee.eddddde...ee..........
    ee.eddddde....ee.........
    ...edddddee....e.........
    ...edddddeee..ee.........
    ...eeeeeee.eeee..........
    ...ee...ee...............
    ...ee...ee...............
    .5555...5555.............
    .5555...5555.............
    `, SpriteKind.Player)
controller.player1.moveSprite(play1)
controller.player2.moveSprite(play1)
controller.player3.moveSprite(play1)
controller.player4.moveSprite(play1)
play1.setPosition(4, 4)
play2.setPosition(146, 6)
play3.setPosition(9, 105)
play4.setPosition(145, 106)
play1.setStayInScreen(true)
play2.setStayInScreen(true)
play3.setStayInScreen(true)
play4.setStayInScreen(true)
info.player1.setLife(3)
info.player2.setLife(3)
info.player3.setLife(3)
info.player4.setLife(3)
